services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - ./data/proxy/data:/data
      - ./data/proxy/letsencrypt:/etc/letsencrypt
    networks:
      default: {}
      br0:
        ipv4_address: ${PROXY_IP}
  
  pihole:
    image: pihole/pihole:latest
    dns:
      - 127.0.0.1
    environment:
      - TZ=${TZ}
      - DNSMASQ_LISTENING=all
    volumes:
      - ./data/pihole/etc-pihole:/etc/pihole
      - ./data/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    networks:
      default: {}
      br0:
        ipv4_address: ${PIHOLE_IP}
    restart: unless-stopped

  borg:
    image: ghcr.io/borgmatic-collective/borgmatic
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    volumes:
      - /home/yanlin:/mnt/home:ro
      - /etc:/mnt/etc:ro
      - ./data/borg/borgmatic.d:/etc/borgmatic.d
      - ./data/borg/repository:/mnt/borg-repository
      - ./data/borg/.config:/root/.config
      - ./data/borg/.ssh:/root/.ssh
      - ./data/borg/.cache:/root/.cache/borg

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_TIMEOUT=30s
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${WATCHTOWER_GOTIFY_URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WATCHTOWER_GOTIFY_TOKEN}


networks:
  br0:
    external: true