services:
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    environment:
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_OCR_LANGUAGES=${PAPERLESS_OCR_INSTALL}
      - PAPERLESS_FILENAME_FORMAT={{ created }}-{{ correspondent }}-{{ title }}
      - PAPERLESS_TIME_ZONE=${TZ}
      - PAPERLESS_URL=https://${PAPERLESS_HOST}
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=https://${PAPERLESS_HOST}
      - PAPERLESS_ALLOWED_HOSTS=${PAPERLESS_HOST}
      - PAPERLESS_CORS_ALLOWED_HOSTS=https://${PAPERLESS_HOST}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PUID=${PUID}
      - PGID=${PGID}
      - CA_TS_FALLBACK_DIR=/usr/src/paperless/data
    volumes:
      - ./data/paperless/config:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_PATH}:/usr/src/paperless/media
      - ${PAPERLESS_CONSUME_PATH}:/usr/src/paperless/consume
      - ${PAPERLESS_EXPORT_PATH}:/usr/src/paperless/export
    depends_on:
      paperless-redis:
        condition: service_healthy
    networks:
      default: {}
      br0:
        ipv4_address: ${PAPERLESS_IP}
  
  paperless-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s
  

networks:
  br0:
    external: true
