services:
  # Scanned document management system
  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    environment:
      - PAPERLESS_REDIS=redis://paperless-redis:6379
      - PAPERLESS_OCR_LANGUAGE=${PAPERLESS_OCR_LANGUAGE}
      - PAPERLESS_OCR_LANGUAGES=${PAPERLESS_OCR_INSTALL}
      - PAPERLESS_FILENAME_FORMAT={{ created }}-{{ correspondent }}-{{ title }}
      - PAPERLESS_TIME_ZONE=${TZ}
      - PAPERLESS_URL=https://${PAPERLESS_HOST}
      - PAPERLESS_CSRF_TRUSTED_ORIGINS=https://${PAPERLESS_HOST}
      - PAPERLESS_ALLOWED_HOSTS=${PAPERLESS_HOST}
      - PAPERLESS_CORS_ALLOWED_HOSTS=https://${PAPERLESS_HOST}
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - USERMAP_UID=${PUID}
      - USERMAP_GID=${PGID}
      - CA_TS_FALLBACK_DIR=/usr/src/paperless/data
    volumes:
      - ./data/paperless/config:/usr/src/paperless/data
      - ${PAPERLESS_MEDIA_PATH}:/usr/src/paperless/media
      - ${PAPERLESS_CONSUME_PATH}:/usr/src/paperless/consume
      - ${PAPERLESS_EXPORT_PATH}:/usr/src/paperless/export
    depends_on:
      paperless-redis:
        condition: service_healthy
    networks:
      - default
      - proxy
    deploy:
      resources:
        limits:
          cpus: 4
  
  # Redis for paperless
  paperless-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s

  docmost:
    image: docmost/docmost:latest
    depends_on:
      docmost-db:
        condition: service_healthy
      docmost-redis:
        condition: service_healthy
    environment:
      APP_URL: "https://note.yanlincs.com"
      APP_SECRET: "MB9ocJ6sZDlGUekMPHEXEhZYGAwc5vod"
      DATABASE_URL: "postgresql://docmost:docmost@docmost-db:5432/docmost?schema=public"
      REDIS_URL: "redis://docmost-redis:6379"
    ports:
      - "3000:3000"
    restart: unless-stopped
    volumes:
      - ${DOCMOST_STORAGE_PATH}:/app/data/storage
    networks:
      - default
      - proxy

  docmost-db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost
      POSTGRES_PASSWORD: docmost
    restart: unless-stopped
    volumes:
      - ./data/docmost/db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "docmost"]
      interval: 10s
      start_period: 30s

  docmost-redis:
    image: redis:7.2-alpine
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 5s


networks:
  br0:
    external: true
  proxy:
    external: true
