services:
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    platform: linux/arm64
    restart: unless-stopped
    volumes:
      - ./data/proxy/data:/data
      - ./data/proxy/letsencrypt:/etc/letsencrypt
    network_mode: host
  
  borg:
    image: ghcr.io/borgmatic-collective/borgmatic
    restart: unless-stopped
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
    volumes:
      - /home/yanlin:/mnt/home:ro
      - /etc:/mnt/etc:ro
      - ./data/borg/borgmatic.d:/etc/borgmatic.d
      - ./data/borg/repository:/mnt/borg-repository
      - ./data/borg/.config:/root/.config
      - ./data/borg/.ssh:/root/.ssh
      - ./data/borg/.cache:/root/.cache/borg

  syncthing:
    image: syncthing/syncthing:latest
    hostname: Pi
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./data/syncthing/config:/var/syncthing/config
      - ${DOC_PATH}:/data
    restart: unless-stopped
    network_mode: host

  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_SCHEDULE=${WATCHTOWER_SCHEDULE}
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_TIMEOUT=30s
      - TZ=${TZ}
      - WATCHTOWER_NOTIFICATIONS_LEVEL=info
      - WATCHTOWER_NOTIFICATIONS=gotify
      - WATCHTOWER_NOTIFICATION_GOTIFY_URL=${WATCHTOWER_GOTIFY_URL}
      - WATCHTOWER_NOTIFICATION_GOTIFY_TOKEN=${WATCHTOWER_GOTIFY_TOKEN}